#!/usr/bin/env bash
# =============================================================================
#  aartool: one front door for the CyberAar hardening toolkit
#
#  DO NOT EDIT THIS FILE. It is built from scripts/aartool-src/ by
#  scripts/build-aartool.sh, the same way cyberaar-baseline.sh is built from
#  scripts/src/. Edit the sources and rebuild.
#
#  WHY THIS EXISTS
#  The toolkit had two entry points with two incompatible conventions for one
#  workflow. cyberaar-baseline.sh took --host and --user; run-hardening.sh took
#  -t and -u. Worse, run-hardening.sh used -t for the target and -T for the
#  tags: a shift key away from each other, on a tool that rewrites sshd_config,
#  PAM and firewall rules.
#
#  aartool wraps both. Neither is replaced and neither changes: they stay
#  independently usable, and cyberaar-baseline.sh keeps the single-file
#  portability that lets you curl it onto an air-gapped box.
#
#  TWO DELIBERATE DIFFERENCES FROM WHAT IT WRAPS
#
#  1. The dry run is a command, not a flag. run-hardening.sh applies changes by
#     default and takes -c to preview them, so forgetting one character is the
#     difference between a report and a rewritten SSH config. Here `plan` shows
#     and `apply` does.
#
#  2. --target is required. run-hardening.sh defaults to the group
#     `linux_servers`, which is every machine in the inventory, so a bare
#     invocation hardens the entire estate. aartool refuses to guess.
# =============================================================================
set -euo pipefail

AARTOOL_VERSION="3.0.0"

# ── Output ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
  CYAN=$'\033[0;36m'; BOLD=$'\033[1m';   RESET=$'\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; CYAN=''; BOLD=''; RESET=''
fi

info()    { printf '%s[INFO]%s  %s\n'  "$CYAN"   "$RESET" "$*"; }
success() { printf '%s[OK]%s    %s\n'  "$GREEN"  "$RESET" "$*"; }
warn()    { printf '%s[WARN]%s  %s\n'  "$YELLOW" "$RESET" "$*" >&2; }

# die() carries the fix, not just the fault. Every message below the first line
# is indented guidance, and it is not decoration: the commonest way a first-time
# user abandons a tool is an error that is accurate and tells them nothing.
die()     { printf '%s[ERROR]%s %s\n'  "$RED"    "$RESET" "$*" >&2; exit 1; }

# --verbose. Off by default because the normal output is the point; on, it says
# what aartool is about to shell out to, which is the only thing that helps when
# it is ansible or ssh that is failing rather than aartool.
AARTOOL_VERBOSE="${AARTOOL_VERBOSE:-0}"
vlog() { [[ "$AARTOOL_VERBOSE" == "1" ]] && printf '%s[..]%s    %s\n' "$CYAN" "$RESET" "$*" >&2; return 0; }

# Show a command before running it, so a failure can be reproduced by hand.
vrun() {
  vlog "run: $*"
  "$@"
}

usage() {
  cat <<'EOF'
aartool: CyberAar hardening toolkit

Usage:
  aartool <command> [options]

Commands:
  inspect     Audit a machine and write HTML + JSON reports. Changes nothing.
  plan        Show what hardening would change on a target. Changes nothing.
  apply       Apply hardening to a target.
  surface     Kernel attack surface: what a local privilege escalation
              would still reach on this machine, and how to close it.
  advise      Turn an audit into an ordered plan: what to fix first, what it
              costs, and the command for each wave.
  explain     What a finding means, what an attacker does with it, and what
              closing it breaks.
  doctor      Check everything plan and apply depend on.
  report      Visualise audit reports, or bake them into one shareable file.
  diff        What changed between two audits. Exits non-zero on a regression.
  install     Put aartool on your PATH.

Global options:
  -h, --help        Show this help, or help for a command
  -v, --verbose     Say what is being run, and where. Use this when something
                    fails and the message is not enough.
  -V, --version     Print the version

Examples:
  # Audit the machine you are on
  sudo aartool inspect

  # Audit one remote host
  aartool inspect --host 10.0.1.10 --user admin

  # See what hardening would do. Nothing is changed.
  aartool plan --target web-01 --user ubuntu

  # SSH hardening only, still a preview
  aartool plan --target web-01 --user ubuntu --only ssh

  # Apply it. Asks you to confirm the target by name.
  aartool apply --target web-01 --user ubuntu

  # What would the next kernel LPE still reach here?
  aartool surface

  # What should I fix first, and what does each fix cost me?
  aartool advise --target web-01 --user ubuntu

  # Why does this finding matter, and what breaks if I close it?
  aartool explain KRN-01

Getting started, on a machine you are sitting at:
  sudo aartool inspect -o ./reports   # 109 checks, changes nothing
  aartool advise                      # the ordered plan, newest report
  aartool explain <ID>                # anything in it you do not know

Run 'aartool <command> --help' for the options of a single command.
Add -v to any command to see what it is running.
EOF
}
