---
- name: "Restart auditd"
  when: "not ansible_check_mode or 'auditd.service' in (aartool_units | default(''))"
  ansible.builtin.service:
    name: "auditd"
    state: "restarted"
  failed_when: false

- name: "Restart rsyslog"
  when: "not ansible_check_mode or 'rsyslog.service' in (aartool_units | default(''))"
  ansible.builtin.service:
    name: "rsyslog"
    state: "restarted"
