---
- name: "Reload and restart tmp.mount"
  when: "not ansible_check_mode or 'tmp.mount' in (aartool_units | default(''))"
  ansible.builtin.systemd:
    name: "tmp.mount"
    state: "restarted"
    daemon_reload: true
  failed_when: false
