---
- name: "Restart journald"
  when: "not ansible_check_mode or 'systemd-journald.service' in (aartool_units | default(''))"
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: "restarted"
    daemon_reload: true
  failed_when: false
